import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/layout/Sidebar";
import FollowBar from "@/components/layout/FollowBar";
import LoginModal from "@/components/modals/LoginModal";
import RegisterModal from "@/components/modals/RegisterModal";
import TweetModal from "@/components/modals/TweetModal";
import Providers from "./providers";
import EditModal from "@/components/modals/EditModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="night">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <TweetModal />
          <LoginModal />
          <RegisterModal />
          <EditModal />

          <div className="h-screen">
            <div className="container h-screen mx-auto xl:px-30 max-w-6xl">
              <div>
                <div className="grid grid-cols-4 h-screen">
                  <Sidebar />
                  <div
                    className="col-span-3 lg:col-span-2 border-x
                    border-base-content/5 "
                  >
                    {children}
                  </div>
                  <FollowBar />
                </div>
              </div>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
